---

- name: restart telegraf
  become: true
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: reload telegraf
  become: true
  ansible.builtin.service:
    name: telegraf
    state: reloaded

- name: validate config
  ansible.builtin.command: |
    /usr/bin/telegraf \
      --debug \
      --test
      --config {{ telegraf_service.config.file }}

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
