---
- name: converge
  hosts: all
  any_errors_fatal: false

  environment:
    NETRC: ''
    # https://github.com/ansible/ansible/issues/77133
    # https://github.com/ansible/ansible/pull/76542
    # LANGUAGE: en_UK.utf8

  roles:
    - role: ansible-telegraf

  pre_tasks:
    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "{{ ansible_system | lower }}"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
